### ISSUE TITLE
User Password or create new user change

### ISSUE THREAD

**Issue by bcmans** [pivotx/PivotX#12]
User password change or create new user results in 

The information you have entered on this page will be sent over an insecure connection and could be read by a third party.
Are you sure you want to send this information?

after this message a new screen (same fields) is shown but does not save anything

PHP 7.4 (ea-php74) 
PivotX - 3.0.0-rc2 (with updates from github
Nothing in error log

**Comment by Darkseid1981** [comment]
That's a scary bug. I'm sure Hans will have a solution for this.

**Comment by hansfn** [comment]
I think this is related to using PivotX with HTTP and not HTTPS. I don't have any issue with this myself, but [googling for the phrase above](https://www.google.com/search?q=The+information+you+have+entered+on+this+page+will+be+sent+over+an+insecure+connection+and+could+be+read+by+a+third+party) gives a lot of hits. It's not a security issue - just a friendly notice - unless you are in fact using HTTPS and the form by error is submitted over HTTP.

Could you provide some more info about your browser, the OS, URL / protocol for your website and so on.

**Comment by Darkseid1981** [comment]
BTW, how did you enable visitor registration? I check the admin options and there's no option for enabling visitor registration.

**Comment by bcmans** [comment]
Hans,

Windows 10
Firefox 114 64 bit
Reaching over https

form.php line 781:
<form  enctype='multipart/form-data'  name='%name%' id='%name%' action="%action%" method='post'>

results in:
<form enctype="multipart/form-data" name="edituser" id="edituser" action="http://mywebsite.com/data/pivotx/index.php?page=useredit&amp;user=admin" method="post">
   

When i change the http into https the form to add/change user works fine.

Hope this helps

Thanks!

**Comment by hansfn** [comment]
Thanks for the additional info. This should actually be handled in [formclass.php line 49](https://github.com/pivotx/PivotX/blob/master/pivotx/modules/formclass.php#L49). I guess that your server is setting `$_SERVER['HTTPS']` to 1 instead of "on". I'll fix the code, but could you add

```
debug("Server['HTTPS']: " . $_SERVER['HTTPS']);

```

on line 47 and then "View debug logs" after trying the operation that fails. (Debug must be enabled.) Or just replace debug with die to get the output ;-) I just want to be sure that we fix it properly.
