### ISSUE TITLE
import_pivot.php

### ISSUE THREAD

**Issue by Darkseid1981** [pivotx/PivotX#6]
It load just fine with no errors, but when you run import nothing else happens. PHP_error_log shows this:

```
PHP Notice:  Only variables should be passed by reference in pivotx/import_pivot.php on line 10
PHP Fatal error:  Uncaught TypeError: array_push(): Argument #1 ($array) must be of type array, null given in pivotx/import_pivot.php:149
Stack trace:
#0 pivotx/import_pivot.php(149): array_push(NULL, '/opt/lampp/htdo...')
#1 pivotx/import_pivot.php(366): start_conversion(Array)
#2 {main}
thrown in pivotx/import_pivot.php on line 149
```

I hope this helps and isn't to difficult to fix.

**Comment by hansfn** [comment]
There are probably multiple problems. I'll fix them on Thursday 1st of June since I also find it useful to be able to convert from flatfile database to MySQL.

PS For other readers: We are discussing and old script that hasn't been moved to GitHuib - [import_pivot.php](https://sourceforge.net/p/pivot-weblog/code/HEAD/tree/misc/import-scripts/import_pivot.php).

**Comment by hansfn** [comment]
I have transferred the script from SourceForge to GitHub and made the necessary fixes for it to work - se https://github.com/pivotx/PivotX-tools
